name = "Personal"
license = "MIT"
licenselink = "https://github.com/PythonPizzaDE/Personal/blob/main/LICENSE"
description = ""
homepage = "https://paulfrische.xyz/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Paul Frische"
  homepage = "https://paulfrische.xyz/"
